USE [master]
GO

/****** Object:  Database [Job Posting]    Script Date: 7/6/2021 2:03:40 PM ******/
CREATE DATABASE [Job Posting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Job Posting', FILENAME = N'C:\Users\PKKostov18\Job Posting.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Job Posting_log', FILENAME = N'C:\Users\PKKostov18\Job Posting_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Job Posting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Job Posting] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Job Posting] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Job Posting] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Job Posting] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Job Posting] SET ARITHABORT OFF 
GO

ALTER DATABASE [Job Posting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Job Posting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Job Posting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Job Posting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Job Posting] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Job Posting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Job Posting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Job Posting] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Job Posting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Job Posting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Job Posting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Job Posting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Job Posting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Job Posting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Job Posting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Job Posting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Job Posting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Job Posting] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Job Posting] SET  MULTI_USER 
GO

ALTER DATABASE [Job Posting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Job Posting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Job Posting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Job Posting] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Job Posting] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Job Posting] SET QUERY_STORE = OFF
GO

USE [Job Posting]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Job Posting] SET  READ_WRITE 
GO


